### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by gbacus**
- added vote counter functionality to server and seed data.

### CODE REVIEW

**Review by 4restM — CHANGES_REQUESTED** [review]
fix them merge conflicts yo

**Comment by gbacus** [comment]
Merge conflicts resolved

**Review by 4restM — CHANGES_REQUESTED** [review]
change true to 1 and false to 0

**Comment by gbacus** [comment]
- added more upvotes/downvotes

**Review by 4restM — APPROVED** [review]
11 thumbs up

**Pull request merged**
